// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// gibbs
List gibbs(NumericMatrix x, int ite, double a = 2.1, double b = 1.1, double gamma_a = 1, double gamma_b = 1, double omega = 10, double omega_1 = 0.01);
RcppExport SEXP slfm_gibbs(SEXP xSEXP, SEXP iteSEXP, SEXP aSEXP, SEXP bSEXP, SEXP gamma_aSEXP, SEXP gamma_bSEXP, SEXP omegaSEXP, SEXP omega_1SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type ite(iteSEXP );
        Rcpp::traits::input_parameter< double >::type a(aSEXP );
        Rcpp::traits::input_parameter< double >::type b(bSEXP );
        Rcpp::traits::input_parameter< double >::type gamma_a(gamma_aSEXP );
        Rcpp::traits::input_parameter< double >::type gamma_b(gamma_bSEXP );
        Rcpp::traits::input_parameter< double >::type omega(omegaSEXP );
        Rcpp::traits::input_parameter< double >::type omega_1(omega_1SEXP );
        List __result = gibbs(x, ite, a, b, gamma_a, gamma_b, omega, omega_1);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
