// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// bfmu_c
NumericMatrix bfmu_c(NumericMatrix x, int ite, double a, double b, double gamma_a, double gamma_b, double omega, double omega_1);
RcppExport SEXP bfm_bfmu_c(SEXP xSEXP, SEXP iteSEXP, SEXP aSEXP, SEXP bSEXP, SEXP gamma_aSEXP, SEXP gamma_bSEXP, SEXP omegaSEXP, SEXP omega_1SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        NumericMatrix x = Rcpp::as<NumericMatrix >(xSEXP);
        int ite = Rcpp::as<int >(iteSEXP);
        double a = Rcpp::as<double >(aSEXP);
        double b = Rcpp::as<double >(bSEXP);
        double gamma_a = Rcpp::as<double >(gamma_aSEXP);
        double gamma_b = Rcpp::as<double >(gamma_bSEXP);
        double omega = Rcpp::as<double >(omegaSEXP);
        double omega_1 = Rcpp::as<double >(omega_1SEXP);
        NumericMatrix __result = bfmu_c(x, ite, a, b, gamma_a, gamma_b, omega, omega_1);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
