# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bfmu_c <- function(x, ite, a, b, gamma_a, gamma_b, omega, omega_1) {
    .Call('bfm_bfmu_c', PACKAGE = 'bfm', x, ite, a, b, gamma_a, gamma_b, omega, omega_1)
}

